/**
 * This file provides the IDL factory for the backend canister
 * It is typically auto-generated by dfx generate, but we provide a fallback
 * implementation to ensure the build succeeds even if generation hasn't run yet
 */

import { IDL } from '@icp-sdk/core/candid';

export const idlFactory = ({ IDL }: { IDL: any }) => {
  const Time = IDL.Int;
  const AddTaskRequest = IDL.Record({
    'assignedTo': IDL.Opt(IDL.Principal),
    'name': IDL.Text,
    'dueDate': IDL.Opt(Time),
    'description': IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin': IDL.Null,
    'user': IDL.Null,
    'guest': IDL.Null,
  });
  const AssignCookingDayRequest = IDL.Record({
    'day': IDL.Text,
    'cook': IDL.Opt(IDL.Principal),
    'cookName': IDL.Opt(IDL.Text),
  });
  const CreateRecurringChoreRequest = IDL.Record({
    'weekday': IDL.Nat,
    'assignedTo': IDL.Opt(IDL.Principal),
    'name': IDL.Text,
    'description': IDL.Text,
  });
  const PersonProfile = IDL.Record({
    'principal': IDL.Principal,
    'displayName': IDL.Text,
    'color': IDL.Text,
  });
  const RecurringChore = IDL.Record({
    'id': IDL.Nat,
    'weekday': IDL.Nat,
    'assignedTo': IDL.Opt(IDL.Principal),
    'name': IDL.Text,
    'createdBy': IDL.Principal,
    'description': IDL.Text,
  });
  const Task = IDL.Record({
    'id': IDL.Nat,
    'assignedTo': IDL.Opt(IDL.Principal),
    'name': IDL.Text,
    'createdBy': IDL.Principal,
    'completed': IDL.Bool,
    'dueDate': IDL.Opt(Time),
    'description': IDL.Text,
    'recurringChoreId': IDL.Opt(IDL.Nat),
  });
  const GetCalendarRequest = IDL.Record({
    'endDate': Time,
    'startDate': Time,
  });
  const CookingAssignment = IDL.Record({
    'day': IDL.Text,
    'assignedBy': IDL.Principal,
    'cook': IDL.Opt(IDL.Principal),
    'cookName': IDL.Opt(IDL.Text),
  });
  const CalendarDay = IDL.Record({
    'tasks': IDL.Vec(Task),
    'date': Time,
    'cookingAssignment': IDL.Opt(CookingAssignment),
  });
  const GetCookingAssignment = IDL.Record({ 'day': IDL.Text });
  const GetTaskRequest = IDL.Record({ 'id': IDL.Nat });
  const FilterByAssigneeRequest = IDL.Record({ 'assignee': IDL.Principal });
  const SortTasksByDueDateRequest = IDL.Record({ 'tasks': IDL.Vec(Task) });
  const UpdateCookingDayRequest = IDL.Record({
    'day': IDL.Text,
    'cook': IDL.Opt(IDL.Principal),
    'cookName': IDL.Opt(IDL.Text),
  });
  const UpdateRecurringChoreRequest = IDL.Record({
    'id': IDL.Nat,
    'weekday': IDL.Nat,
    'assignedTo': IDL.Opt(IDL.Principal),
    'name': IDL.Text,
    'description': IDL.Text,
  });

  return IDL.Service({
    'addTask': IDL.Func([AddTaskRequest], [IDL.Nat], []),
    'assignCallerUserRole': IDL.Func([IDL.Principal, UserRole], [], []),
    'assignCookingDay': IDL.Func([AssignCookingDayRequest], [], []),
    'clearCompletedTasks': IDL.Func([], [], []),
    'createRecurringChore': IDL.Func([CreateRecurringChoreRequest], [IDL.Nat], []),
    'deleteProfile': IDL.Func([IDL.Principal], [], []),
    'deleteRecurringChore': IDL.Func([IDL.Nat], [], []),
    'deleteTask': IDL.Func([IDL.Nat], [], []),
    'getAllProfiles': IDL.Func([], [IDL.Vec(PersonProfile)], ['query']),
    'getAllRecurringChores': IDL.Func([], [IDL.Vec(RecurringChore)], ['query']),
    'getAllTasks': IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCalendar': IDL.Func([GetCalendarRequest], [IDL.Vec(CalendarDay)], ['query']),
    'getCallerUserRole': IDL.Func([], [UserRole], ['query']),
    'getCompletedTasks': IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCookingAssignment': IDL.Func([GetCookingAssignment], [CookingAssignment], ['query']),
    'getCookingAssignments': IDL.Func([], [IDL.Vec(CookingAssignment)], ['query']),
    'getPendingTasks': IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getProfile': IDL.Func([IDL.Principal], [PersonProfile], ['query']),
    'getRecurringChore': IDL.Func([IDL.Nat], [RecurringChore], ['query']),
    'getTask': IDL.Func([GetTaskRequest], [Task], ['query']),
    'getTasksByAssignee': IDL.Func([FilterByAssigneeRequest], [IDL.Vec(Task)], ['query']),
    'getTasksByDate': IDL.Func([Time], [IDL.Vec(Task)], ['query']),
    'isCallerAdmin': IDL.Func([], [IDL.Bool], ['query']),
    'sortTasksByDueDate': IDL.Func([SortTasksByDueDateRequest], [IDL.Vec(Task)], ['query']),
    'toggleTaskCompletion': IDL.Func([IDL.Nat], [], []),
    'updateCookingDay': IDL.Func([UpdateCookingDayRequest], [], []),
    'updateRecurringChore': IDL.Func([UpdateRecurringChoreRequest], [], []),
    'updateTask': IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(Time), IDL.Opt(IDL.Principal)], [], []),
    'upsertProfile': IDL.Func([PersonProfile], [], []),
    '_initializeAccessControlWithSecret': IDL.Func([IDL.Text], [], []),
  });
};
