/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddTaskRequest {
  'assignedTo' : [] | [Principal],
  'name' : string,
  'dueDate' : [] | [Time],
  'description' : string,
}
export interface AssignCookingDayRequest {
  'day' : string,
  'cook' : [] | [Principal],
  'cookName' : [] | [string],
  'description' : string,
}
export interface CalendarDay {
  'tasks' : Array<Task>,
  'date' : Time,
  'cookingAssignment' : [] | [CookingAssignment],
}
export interface CookingAssignment {
  'day' : string,
  'assignedBy' : Principal,
  'cook' : [] | [Principal],
  'cookName' : [] | [string],
  'description' : string,
}
export interface CreateRecurringChoreRequest {
  'weekday' : bigint,
  'assignedTo' : [] | [Principal],
  'name' : string,
  'description' : string,
  'timeline' : Timeline,
}
export interface FilterByAssigneeRequest { 'assignee' : Principal }
export interface GetCalendarRequest { 'endDate' : Time, 'startDate' : Time }
export interface GetCookingAssignment { 'day' : string }
export interface PauseResumeChoreRequest { 'id' : bigint, 'pause' : boolean }
export interface PersonProfile {
  'principal' : Principal,
  'displayName' : string,
  'color' : string,
}
export interface RecurringChore {
  'id' : bigint,
  'weekday' : bigint,
  'assignedTo' : [] | [Principal],
  'name' : string,
  'createdBy' : Principal,
  'description' : string,
  'paused' : boolean,
  'timeline' : Timeline,
}
export interface SortTasksByDueDateRequest { 'tasks' : Array<Task> }
export interface Task {
  'id' : bigint,
  'assignedTo' : [] | [Principal],
  'name' : string,
  'createdBy' : Principal,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'description' : string,
  'recurringChoreId' : [] | [bigint],
}
export type Time = bigint;
export type Timeline = { 'fortnightly' : null } |
  { 'weeklies' : null } |
  { 'monthly' : null } |
  { 'daily' : null };
export interface UpdateCookingDayRequest {
  'day' : string,
  'cook' : [] | [Principal],
  'cookName' : [] | [string],
  'description' : string,
}
export interface UpdateMealDescriptionRequest {
  'day' : string,
  'description' : string,
}
export interface UpdateRecurringChoreRequest {
  'id' : bigint,
  'weekday' : bigint,
  'assignedTo' : [] | [Principal],
  'name' : string,
  'description' : string,
  'timeline' : Timeline,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTask' : ActorMethod<[AddTaskRequest], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignCookingDay' : ActorMethod<[AssignCookingDayRequest], undefined>,
  'clearCompletedTasks' : ActorMethod<[], undefined>,
  'createRecurringChore' : ActorMethod<[CreateRecurringChoreRequest], bigint>,
  'deleteProfile' : ActorMethod<[Principal], undefined>,
  'deleteRecurringChore' : ActorMethod<[bigint], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getActiveRecurringChores' : ActorMethod<[], Array<RecurringChore>>,
  'getAllProfiles' : ActorMethod<[], Array<PersonProfile>>,
  'getAllRecurringChores' : ActorMethod<[], Array<RecurringChore>>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getCalendar' : ActorMethod<[GetCalendarRequest], Array<CalendarDay>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTasks' : ActorMethod<[], Array<Task>>,
  'getCookingAssignment' : ActorMethod<
    [GetCookingAssignment],
    CookingAssignment
  >,
  'getCookingAssignments' : ActorMethod<[], Array<CookingAssignment>>,
  'getPendingTasks' : ActorMethod<[], Array<Task>>,
  'getProfile' : ActorMethod<[Principal], PersonProfile>,
  'getRecurringChore' : ActorMethod<[bigint], RecurringChore>,
  'getTask' : ActorMethod<[bigint], Task>,
  'getTasksByAssignee' : ActorMethod<[FilterByAssigneeRequest], Array<Task>>,
  'getTasksByDate' : ActorMethod<[Time], Array<Task>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'pauseResumeRecurringChore' : ActorMethod<
    [PauseResumeChoreRequest],
    undefined
  >,
  'sortTasksByDueDate' : ActorMethod<[SortTasksByDueDateRequest], Array<Task>>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
  'updateCookingDay' : ActorMethod<[UpdateCookingDayRequest], undefined>,
  'updateMealDescription' : ActorMethod<
    [UpdateMealDescriptionRequest],
    undefined
  >,
  'updateRecurringChore' : ActorMethod<
    [UpdateRecurringChoreRequest],
    undefined
  >,
  'updateTask' : ActorMethod<
    [bigint, string, string, [] | [Time], [] | [Principal]],
    undefined
  >,
  'upsertProfile' : ActorMethod<[PersonProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];